feat: D1 API conformance
tablelandnetwork/tableland-js pull request #63
Opened 2023-10-28 01:17 UTC by dtbuchholz

## Summary

The D1 API changed, so our API is no longer compatible. This introduces some breaking changes since some of the statement & database methods' parameters, generic types, and returned types have to be altered for conformance purposes.

## Details

For reference, [these are the old](https://github.com/cloudflare/workerd/commit/72d6915e19fb56de8373144bf922afa253b378cc) APIs, and [these are the new ones](https://github.com/cloudflare/workerd/blob/main/types/defines/d1.d.ts). The interfaces the statement methods must conform to are the following—notice the generic type `T = unknown` is now `T = Record<string, unknown>` in most of these:

```ts
// old
bind(...values: any[]): D1PreparedStatement;
first<T = unknown>(colName?: string): Promise<T>;
run<T = unknown>(): Promise<D1Result<T>>;
all<T = unknown>(): Promise<D1Result<T>>;
raw<T = unknown>(): Promise<T[]>;

// new
bind(...values: unknown[]): D1PreparedStatement;
first<T = unknown>(colName: string): Promise<T | null>;
first<T = Record<string, unknown>>(): Promise<T | null>;
run<T = Record<string, unknown>>(): Promise<D1Result<T>>;
all<T = Record<string, unknown>>(): Promise<D1Result<T>>;
raw<T = unknown[]>(): Promise<T[]>;
```

None of the database methods have changed, except for `exec`, which now has a custom return type:

```ts
// old
interface D1Result<T = unknown> {
  results?: T[];
  success: boolean;
  error?: string;
  meta: any;
}
exec<T = unknown>(query: string): Promise<D1Result<T>>;

// new
interface D1ExecResult {
  count: number;
  duration: number;
}
exec(query: string): Promise<D1ExecResult>;
```

From a DX perspective, the following changes should be noted. It wasn't clear if all of these changes were necessary as I was simply comparing and trying to go 1:1 to the new D1 API:
- Removed `colName` parameter for the statement methods, except `first`.
- Changed generic types for relevant statement methods to use `T = Record<string, S>` instead of `T = S`, where `S = unknown`.
- For `exec`, it no longer can use the same `Result` we had—a new `ExecResult` interface has been added, and a `wrapExecResult` properly formats the data for the `exec` return type.
  - This introduces one notable breaking change—since this interface only requires `count` and `duration`, the typical `meta` object cannot be required.
  - Thus, instead of a pattern for mutating queries like `await meta.txn?.wait()`, it looks like `await txn?.wait()`.

## How it was tested

Altered existing tests to take these changes into account. It primarily affected the `exec` method since it uses a new interface that doesn't contain `meta`. Also, it's worth nothing the `d1-orm`, ironically, _doesn't_ include the latest API changes. The 3rd party / ORM tests will fail for `d1-orm`, so I've commented them out. (I've actually opened a PR in that repo to try and get it resolved [here](https://github.com/Interactions-as-a-Service/d1-orm/pull/71)).

Note: it looks like I also included a new test for `getChainPollingController`, which is more relevant to https://github.com/tablelandnetwork/tableland-js/pull/36.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-10-28 01:23 UTC, dtbuchholz commented on packages/sdk/src/database.ts
> +      return wrapExecResult(result, count);
This return type had to be altered to use `ExecResult`, which looks like this:
```ts
interface ExecResult<T = unknown>
  count: number;
  duration: number;
  txn?: WaitableTransactionReceipt;
  results?: T[];
}
```
The D1 API only requires `count` and `duration`. This is where the DX component comes into play because everything _except_ this method can use the `meta.txn?.wait()` pattern, but this needs to do `txn?.wait()`. 

Instead of `ExecResult` having a `txn?` field, I debated making it a `meta?` field...but that means usage would look like `meta?.txn?.wait()`, and the `meta?` being a bit confusing imo.

2023-10-28 01:25 UTC, dtbuchholz commented on packages/sdk/src/database.ts
> +      return wrapExecResult(result, count);
Also, this method could be refactored, if needed. It just takes the result from `await statement.run(..)`, which means we're really calling `wrapResult` and then passing that value to `wrapExecResult`. But, I figured I'd keep it simple in case any of this isn't the right approach.

2023-10-28 01:25 UTC, dtbuchholz commented on packages/sdk/src/registry/utils.ts
> +export interface ExecResult<T = unknown>
Here's the `ExecResult`, for reference.

2023-10-28 01:26 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async all<T = Record<string, S>>(opts: Options = {}): Promise<Result<T>> {
Generic type change for API conformance.

2023-10-28 01:29 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async first<T = Record<string, S>>(opts?: Options): Promise<T | null>;
Generic type change for API conformance.

Also, I wasn't sure if the lines I deleted were necessary with the addition of this method above, but I could be wrong so lmk if I should add any of those back in.

2023-10-28 01:31 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async run<T = Record<string, S>>(opts: Options = {}): Promise<Result<T>> {
Generic type change for API conformance. Also, I'm not sure if removing that `never` is correct...I was just basing it off of the D1 API, which expects a `Result<T>` [here](https://github.com/cloudflare/workerd/blob/875a5171d1ec52d3bff63fa0e599975a769956f1/types/defines/d1.d.ts#L24).

2023-10-28 01:32 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async raw<T = S[]>(opts: Options = {}): Promise<Array<ValueOf<T>>> {
Generic type change, seen [here](https://github.com/cloudflare/workerd/blob/875a5171d1ec52d3bff63fa0e599975a769956f1/types/defines/d1.d.ts#L26).

2023-10-28 01:33 UTC, dtbuchholz commented on packages/sdk/test/chains.test.ts
> +  describe("getChainPollingController()", function () {
These are the tests that should probably be in https://github.com/tablelandnetwork/tableland-js/pull/36, so they're not related to the D1 conformance.

2023-10-28 01:33 UTC, dtbuchholz commented on packages/sdk/test/database.test.ts
> +      const { duration, count, txn } = await db.exec(sql);
This shows how `exec` usage has changed. It feels _almost_ the same...just with top-level fields vs. nested in `meta`.

2023-10-28 01:35 UTC, dtbuchholz commented on packages/sdk/test/thirdparty.test.ts
> +  // NOTE: the d1-orm hasn't updated to the latest version of @cloudflare/workers-types
Lastly, the `d1-orm` test has been commented out since the ORM actually isn't bumped to the latest version of `@cloudflare/workers-types`

2023-10-28 02:13 UTC, dtbuchholz commented
(Also, looks like a test failed for `@tableland/local` due to the `exec` change, but I'll wait to clean that up to make sure these changes are the correct approach.)

2023-10-31 09:33 UTC, joewagner requested changes
@dtbuchholz This looks pretty good so far.  I have a PR with some suggested additions to make the SDK D1 and typescript all work together here: https://github.com/tablelandnetwork/tableland-js/pull/65

2023-10-31 09:50 UTC, joewagner commented
In regard to versioning.
I think these changes would indicate a major bump right?  I'm not sure why d1-orm didn't do a major, but I guess since they are still version `0.x.x` they can break things without a major bump

2023-10-31 09:55 UTC, joewagner commented
> does lerna automatically use whatever code is present in other packages? e.g., for `local`, I didn't change up its deps at all, but a `local` test that used the `sdk` package's `exec` no longer worked due to the SDK's breaking change. in other words, the published version for `@tableland/sdk` is the listed dependency for `local`, but the `local` tests were using the SDK changes from this PR.

I think that's how lerna is designed to work.  If you need to have incompatible packages in the same commit I think you can pin an older version of `sdk` in the `local` package.lock, but I'm not sure.

2023-10-31 17:35 UTC, dtbuchholz commented on packages/sdk/src/database.ts
> +      return wrapExecResult(result, count);
cool, issue created [here](https://linear.app/tableland/issue/STU-164/web-aborted-signal-during-table-creation-in-ui)...should be a quick fix so i can take it on

2023-10-31 17:37 UTC, dtbuchholz commented
> I think these changes would indicate a major bump right? I'm not sure why d1-orm didn't do a major, but I guess since they are still version `0.x.x` they can break things without a major bump

@joewagner correct, we'll need a major version. and also correct—the d1-orm maintainer said that pre-major version, they're just keeping all breaking changes as minor versions.

2023-10-31 20:16 UTC, dtbuchholz commented on packages/sdk/test/thirdparty.test.ts
> +    const database = drizzle(db, { schema: { user } });
@joewagner i merged your PR to resolve the other `@ts-expect-error`s in this test (thanks for that!). and this last one turned out to be more of an error on my side, so it's been fixed, too.

2023-11-01 02:30 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async raw<T = unknown>(opts: Options = {}): Promise<Array<ValueOf<T>>> {
@joewagner oh actually, i have a question with this one. the [new API](https://github.com/cloudflare/workerd/blob/7314c771b6ca85bdc5d0b00592e889769d40eec7/types/defines/d1.d.ts#L26) uses:
```ts
raw<T = unknown[]>(): Promise<T[]>;
```
what's the reason you used `T = unknown` over `T = S[]` (where `S = unknown`)? is it more flexible to how we implement the underlying logic or something like that?

2023-11-01 09:04 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async first<T = Record<string, S>>(opts?: Options): Promise<T | null>;
As discussed in #36, I've added back the overload that has `colName: undefined`. (I think I was a bit confused on how it worked, but it's much clearer now.)

After some testing, I also updated the generic to `K extends keyof T & string = keyof T & string`. Before, it was technically possible for `K` to be a non-string value, so I altered this to help enforce the D1 `string` requirement for `colName`.

2023-11-01 09:05 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  #checkIsValidOpts(opts: any): opts is Options {
More on this below. It does a check on a passed arg to make sure it is a valid `Options` object with a valid `PollingController`. If not, the rest of the logic is handled in the `first` impl.

2023-11-01 09:15 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +      // Handle first overload to ensure passed `opts` are not set to `colName`
I discovered that if you try and use the top-most overload for `first()` and pass your own `opts`, the compiler sees the `opts` as `colName`, which obv isn't correct.

for example, running something like this would fail because the passed `opts`/controller was seen as the _first_ param...so then, the `extractColumn` method would try and use the `opts` as the `colName`.
```ts
await stmt.first<{ counter: number; info: string }>({
  controller,
})
```
in other words, before this new new logic, it would see this:
```
colName
{
  controller: {
    signal: AbortSignal { aborted: false },
    abort: [Function: abort],
    interval: 1500,
    cancel: [Function: cancel],
    timeout: 60000
  }
}
opts
{}
```
and with the new logic, it'll properly set colName/opts and use them thereafter.

2023-11-01 09:42 UTC, joewagner commented on packages/sdk/src/statement.ts
> +  async raw<T = unknown>(opts: Options = {}): Promise<Array<ValueOf<T>>> {
I didn't think about it much.  I ran the tests and saw that there was a type mismatch, then I just copied the D1 types exactly as they are on the [main branch](https://github.com/cloudflare/workerd/blob/main/types/defines/d1.d.ts#L26) and the tests passed.  You probably have more context then me, what was the reason for `T = S[]` (where `S = unknown`)?

2023-11-01 10:11 UTC, joewagner commented on packages/sdk/src/statement.ts
> +  async raw<T = unknown>(opts: Options = {}): Promise<Array<ValueOf<T>>> {
Looks like it's defined in the constructor, that might work better? Feel free to switch it back.

2023-11-01 10:14 UTC, joewagner approved these changes

2023-11-01 23:32 UTC, dtbuchholz commented on packages/sdk/src/statement.ts
> +  async raw<T = unknown>(opts: Options = {}): Promise<Array<ValueOf<T>>> {
ahh i see what you did re: the tests and 3rd party libs. _nooow_ it makes sense!

and nre: the way in which we implement `raw` with `T = S` seems to work just fine, even though the D1 API expects `T = S[]`. i think it's due to our impl where we return `Array<ValueOf<T>>`, which will properly adhere to the D1 return type `T[]` because of the of `ValueOf`.

2023-11-02 00:11 UTC, sanderpick approved these changes
awesome! great work.

2023-11-02 00:25 UTC, merged